#!/bin/sh

commit_msg_file=$1
commit_msg=$(cat "$commit_msg_file")

# Regex: type(scope?): description
conventional_regex="^(feat|fix|docs|style|refactor|perf|test|chore|build|ci|revert)(\([a-zA-Z0-9_-]+\))?: .{1,}"

if echo "$commit_msg" | grep -Eq "$conventional_regex"; then
  echo "✅ Commit message format is valid."
  exit 0
else
  echo "❌ Invalid commit message format!"
  echo ""
  echo "👉 Format should be: type(scope?): description"
  echo "   Examples:"
  echo "     feat(auth): add JWT refresh token support"
  echo "     fix(url): handle expired short links"
  echo "     chore: setup husky hooks"
  exit 1
fi